---
title: "Post 1"
author: ""
date: "2024-02-28"
date-modified: "2024-02-28"
draft: FALSE
---
# Data Set 2: [Iowa Probation Recidivism Status](https://data.iowa.gov/Correctional-System/Iowa-Probation-Recidivism-Status/pax6-5xni/about_data)

This dataset contains deidentified case level records of individuals starting probation supervision in the community. Data begins with the FY 2016 cohort. It also provides an individual's status at three years to assess whether probation was successful or whether the individual was reincarcerated. The dataset appears to detail recidivism among individuals released from prison, focusing on various demographic, legal, and post-release supervisory characteristics. The following are the definition on variables in each column:

Race: The individual's race or ethnicity.
Sex: The individual's biological sex.
Age: The individual's age at start of probation.
Under 18: Indicator if the individual was under 18 years old at start of probation.
Supervising Region Name: Name of the primary region supervising the individual.
Work Unit Name: Name of the primary work unit supervising the individual.
Jurisdiction: Iowa county with primary jurisdiction.
Cohort Fiscal Year: The fiscal year the individual began probation. The fiscal year runs from July 1 through June 30, and is labeled for the calendar year that it ends.
Report Fiscal Year: The fiscal year in which probation is deemed successful. The fiscal year runs from July 1 through June 30, and is labeled for the calendar year that it ends.
Supervision Start Date: Start date of supervision, or earliest start date of concurrent or overlapping sentences.
Supervision End Date: End date of supervision, or latest end date of concurrent or overlapping sentences.
Time Served (Months): The number of months the individual has served on probation.
Supervision Offense Class: The classification of the most serious offense the individual was convicted of and being supervised for. Includes one of the following: Aggravated Misdemeanor, B Felony, C Felony, D Felony, Felony - Enhancement to Original Penalty, Other Felony, Serious Misdemeanor, Simple Misdemeanor, or Other Misdemeanor..
Supervision Offense Type: The offense type of the most serious offense the individual was convicted of and being supervised for. Includes one of the following: Drug, Other, Property, Public Order, or Violent.
Supervision Offense Subtype: The offense subtype of the most serious offense the individual was convicted of and being supervised for. Includes one of the following: Assault, Alcohol, Animals, Arson, Burglary, Drug Possession, Flight/Escape, Forgery/Fraud, Kidnap, Murder/Manslaughter, Other Criminal, Other Drug, Other Government, Other Public Order, Other Violent, OWI, Prostitution/Pimping, Robbery, Sex, Stolen Property, Theft, Traffic, Trafficking, Vandalism, or Weapons.
Supervision Offense Description: Description of the most serious offense the individual was convicted of and being supervised for.
Reincarcerated: Indicator of whether the individual was incarcerated within three years of probation starting..
Reincarcerated Reason: Indicates whether the individual was incarcerated due to being convicted for a new crime or for a technical violation. Null where the individual was not incarcerated.
Prison Supervision Start Date: Start date of prison supervision where the individual was incarcerated. Null if the individual was not incarcerated.
Prison Supervision End Date: End date of prison supervision where the individual was incarcerated. Null if the individual was not incarcerated.
Reincarcerated Offense Code: The code found in Iowa law book for most serious crime the individual was convicted of that resulted in the individual being incarcerated. Null where the individual was not incarcerated.
Reincarcerated Offense Class: The classification of the most serious offense the individual was incarcerated for. Includes one of the following: A Felony, Aggravated Misdemeanor, B Felony, C Felony, D Felony, Felony - Enhancement to Original Penalty, Felony - Mandatory Minimum, Other Felony, Serious Misdemeanor, Simple Misdemeanor, or Special Sentence 2005. Null where the individual was not incarcerated.
Reincarcerated Offense Type: The offense type of the most serious offense the individual was incarcerated for. Includes one of the following: Drug, Other, Property, Public Order, or Violent. Null where the individual was not incarcerated.
Reincarcerated Offense Subtype: The offense subtype of the most serious offense the individual was incarcerated for. Includes one of the following: Assault, Alcohol, Animals, Arson, Burglary, Drug Possession, Flight/Escape, Forgery/Fraud, Kidnap, Murder/Manslaughter, Other Criminal, Other Drug, Other Government, Other Public Order, Other Violent, OWI, Prostitution/Pimping, Robbery, Sex, Stolen Property, Theft, Traffic, Trafficking, Vandalism, or Weapons. Null where the individual was not incarcerated.
Offense Date: The date of the offense resulting in the individual's incarceration. Null where the individual was not incarcerated.
Survival Time (Days): Provides the number of days the individual was in the community before being incarcerated. Null where the individual was not incarcerated.
Survival Time (Months): Provides the number of months (days/30) the individual was in the community before being incarcerated. Null where the individual was not incarcerated.
Supervision Level: Supervision level assigned to the individual. Options include Levels 1-5. Level 0 indicates risk assessment has not been conducted for the individual.
Current Year: "Yes" where the report fiscal year is the most current fiscal year.
  
The dataset is in a csv file, so it is able to load and clean. From the dataset, we want to explore on the question that are there disparities in recidivism rates among racial-ethnic groups when considering the supervising district?

