---
title: "Post 2: Project Update"
subtitle: "Data Background + Loading and Cleaning + Data for Equity"
author: ""
date: "2024-03-22"
date-modified: "2024-03-22"
draft: FALSE
---

After discussion, we decided to choose the data set about COMPAS Recidivism Racial Bias. We took time to investigate the data, so we found the original source about the data. Then, we did data loading and cleaning. At last, we read the article on Data for Equity Principals and thought about how the data could be applied on our data. And, we wrote several paragraphs about limitations of your analysis and the potential for abuse or misuse of the data.

Data for Equity:
The principles for advancing equitable data practice that are most relevant to our data set are beneficence and transparency.
The principle of beneficence demands that the collection, analysis, and dissemination of data on probation recidivism actively seek to benefit the individuals and communities represented within the dataset. Given the dataset’s focus on potentially sensitive topics like criminal justice outcomes, adhering to this principle means conducting analyses that aim to identify and address systemic inequalities rather than reinforcing existing prejudices or biases. In practice, this involves meticulous analysis and presentation of recidivism data to ensure that it does not inadvertently stigmatize individuals based on race, ethnicity, or other demographic characteristics. 
Transparency is another critical principle, especially in acknowledging the dataset’s limitations and the context of its collection and analysis. 
Transparency about the limitations inherent in recidivism research includes acknowledging biases within the criminal justice system that affect who is placed under probation and the conditions of their supervision. Practicing transparency involves clear communication about the analysis’s scope, the assumptions made, and the measures taken to protect the privacy and dignity of the individuals represented in the data. This includes being clear about the geographical and temporal scope of the analysis, the definitions of probation success or failure, and the inherent uncertainties in measuring and predicting recidivism.
Our data set faces limitations that might not fully capture the complex factors influencing recidivism, such as access to support services and community reintegration programs. Additionally, there could be biases in data collection and reporting processes.